version: '3'

services:
  # Postgres DB for data storage
  postgres:
    image: 'postgres:11.1'
    volumes:
      - ./docker_pg_data:/var/lib/postgresql
    ports:
      - '5432:5432'
    command: "-c 'shared_buffers=1024MB' -c 'max_connections=300'"

  dependencies:
    image: 'jwilder/dockerize:0.6.1'
    command: >
      echo "Go Wild!"
    depends_on:
      - postgres
